-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users table (extends auth.users)
create table public.users (
  id uuid references auth.users(id) on delete cascade not null primary key,
  email text,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Projects table
create table public.projects (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- API Keys table
create table public.api_keys (
  id uuid default uuid_generate_v4() primary key,
  key_hash text unique not null,
  user_id uuid references public.users(id) on delete cascade not null,
  project_id uuid references public.projects(id) on delete cascade not null,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Runs table
create table public.runs (
  id text primary key, -- run_id is a string like "run_..."
  project_id uuid references public.projects(id) on delete cascade not null,
  user_id uuid references public.users(id) on delete set null,
  name text,
  task text,
  status text default 'running',
  start_time timestamp with time zone default timezone('utc'::text, now()),
  end_time timestamp with time zone,
  video_path text,
  video_start_time timestamp with time zone,
  laminar_trace_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Events table
create table public.events (
  id bigint generated by default as identity primary key,
  run_id text references public.runs(id) on delete cascade not null,
  type text not null,
  payload text not null, -- JSON content stored as text
  timestamp timestamp with time zone default timezone('utc'::text, now()),
  video_timestamp float
);

-- Security Findings table
create table public.security_findings (
  id bigint generated by default as identity primary key,
  run_id text references public.runs(id) on delete cascade not null,
  severity text not null,
  category text not null,
  description text not null,
  evidence text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS Policies (Optional but recommended)
alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.api_keys enable row level security;
alter table public.runs enable row level security;
alter table public.events enable row level security;
alter table public.security_findings enable row level security;

-- Simple policies allowing full access to authenticated users for now (refine later)
create policy "Users can view their own data" on public.users for select using (auth.uid() = id);
create policy "Users can update their own data" on public.users for update using (auth.uid() = id);

create policy "Users can view their projects" on public.projects for select using (auth.uid() = user_id);
create policy "Users can create projects" on public.projects for insert with check (auth.uid() = user_id);
create policy "Users can update their projects" on public.projects for update using (auth.uid() = user_id);
create policy "Users can delete their projects" on public.projects for delete using (auth.uid() = user_id);

-- Trigger to create public.users entry on auth.users insert
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
